---
- name: Install prerequisites for Docker repository
  apt:
    name:
     - ca-certificates
     - curl
     - gnupg2
     - software-properties-common

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- block:
  - name: Install fuse-overlayfs for LXC hosts
    apt:
      name: fuse-overlayfs

  - name: Fix config to use fuser-overlayfs
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      mode: 0644
      owner: root
      group: root
  when:
    - ansible_virtualization_type is defined
    - ansible_virtualization_type == 'lxc'
